name = "eq-line-bot"
compatibility_date = "2024-08-17"


account_id = "4270d8a14dfc1f866629099a788c93e2"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
placement = { mode = "smart" }

rules = [{ type = "Data", globs = ["**/*.csv"], fallthrough = true }]
